### ISSUE TITLE
LM studio does not detect the available VRAM

### ISSUE THREAD

**Issue by khordoo-m** [lmstudio-ai/.github#17]
Hi, I have a Windows 10 laptop with an NVIDIA RTX A2000 Laptop GPU with about 20GB of VRAM. However, when I run LM Studio, the available VRAM is displayed as 0, as shown in the picture below. Essentially LM Studio fails to identify the VRAM available on my laptop
![image](https://github.com/lmstudio-ai/.github/assets/67798995/5b02f292-7955-4e8c-8437-21df16dc13a8)

**Comment by yagil** [comment]
Possible workaround, could you please let me know if it works on your setup?

1. open LM Studio, navigate to the Chat page
2. check the GPU Offload checkbox. Does not matter what value you put for n layers
3. hard exit LM Studio
4. reopen it

**Comment by khordoo-m** [comment]
This workaround worked. Thanks!

**Comment by khordoo-m** [comment]
This workaround worked. Thanks!
