### ISSUE TITLE
can not download model in lmstudio ui

### ISSUE THREAD

**Issue by CHDyshli** [lmstudio-ai/.github#37]
can't search, can't download.
The system is win11. I use Clash to connect huggingface and other web, the clash config I use is rule mode. I also have tried global mode, but both are not work.
I can access huggingface.co in the brower, but the lmstudion app can not. I don't know why.
![image](https://github.com/lmstudio-ai/.github/assets/111059367/7f58bb40-30c6-498f-86c8-0239d208c4d1)
![image](https://github.com/lmstudio-ai/.github/assets/111059367/32b8a320-5f6d-42a6-bf31-9d5b9b84368f)

**Comment by oracle9i88** [comment]
+1

**Comment by oracle9i88** [comment]
ipv6 fine
hugging face fine
