### ISSUE TITLE
Unable to load any models on Linux

### ISSUE THREAD

**Issue by ericlay** [lmstudio-ai/.github#40]
I have been unable to get any models to load when testing on Linux. I do not have the same issues on Windows 10/11 (works great there). Even on the same device.

I have tried on 3 separate devices with varying OS:

Desktop 1: Debian 12.5/AMD Ryzen5-5600x/32G/RX6600
Desktop 2: Windows 10/Intel Core i7-6700/16G
Laptop: Dual boot - Windows 11 + Arch/Intel Core i7-1255u/16G/Intel Arc 370

Installed by: Windows - using the installer package on lmstudio.ai / Arch - using the AUR package / Debian - downloading the appimage and running from terminal ala ./ 

I don't have any issues running under Windows on either device but run into the same issue on both Arch and Debian. Unused ram is always reported as ~24-25KB, while various tools are showing ~18G free ram.

Latest error on Debian desktop (sometimes the code is 11 other times 0):
```json
{
  "cause": "(Exit code: 11)?. Please check settings and try loading the model again. ",
  "suggestion": "",
  "data": {
    "memory": {
      "ram_capacity": "27.30 GB",
      "ram_unused": "28.25 KB"
    },
    "gpu": {
      "type": "AmdOpenCL",
      "vram_recommended_capacity": 0,
      "vram_unused": 0
    },
    "os": {
      "platform": "linux",
      "version": "6.6.15-amd64",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.19",
      "downloadsDir": "/home/eric/.cache/lm-studio/models"
    },
    "model": {}
  },
  "title": "Error loading model."
}```

**Comment by SKajto** [comment]
The same issue:

```json
{
  "cause": "(Exit code: 0)?. Please check settings and try loading the model again. ",
  "suggestion": "",
  "data": {
    "memory": {
      "ram_capacity": "125.67 GB",
      "ram_unused": "127.67 KB"
    },
    "gpu": {
      "type": "AmdOpenCL",
      "vram_recommended_capacity": 0,
      "vram_unused": 0
    },
    "os": {
      "platform": "linux",
      "version": "6.1.0-1036-oem",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.20",
      "downloadsDir": "/home/skajto/.cache/lm-studio/models"
    },
    "model": {}
  },
  "title": "Error loading model."
}

```

### System Info:

- System:
  Kernel: 6.1.0-1036-oem x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
- Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: TUF GAMING B550M-PLUS v: Rev X.0x serial: <superuser required>
    UEFI: American Megatrends v: 2803 date: 04/27/2022
- CPU:
  Info: 8-core model: AMD Ryzen 7 5700X bits: 64 type: MT MCP arch: Zen 3 rev: 2 cache:
    L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2812 high: 3631 min/max: 2200/4936 boost: disabled cores: 1: 3600 2: 3600
    3: 3631 4: 3589 5: 3593 6: 2200 7: 2200 8: 2200 9: 2200 10: 2200 11: 2200 12: 2200 13: 2200
    14: 2200 15: 3591 16: 3598 bogomips: 115196
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
- Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: Sapphire Nitro+
    driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports: active: HDMI-A-2
    empty: DP-1, DP-2, DVI-D-1, HDMI-A-1 bus-ID: 07:00.0 chip-ID: 1002:67df
  OpenGL: renderer: AMD Radeon RX 570 Series (polaris10 LLVM 15.0.7 DRM 3.49 6.1.0-1036-oem)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes

**Comment by peterxie1** [comment]
I saw the same issue, cannot load any models with LM studio 0.2.18 on Ubuntu20.04. i saw error: "(exit code: 42)?. Please check settings and try loading the model again. "
Anyone get it working on Linux?

**Comment by thinkORo** [comment]
I had an older version (0.2.16) up and running. Since 0.2.18 (today 0.20.0) LM studio cannot load any model.

**Comment by JAvilaSP** [comment]
Same problem here, Ubuntu 22.04.4
```json
{
  "cause": "(Exit code: 0)?. Please check settings and try loading the model again. ",
  "suggestion": "",
  "data": {
    "memory": {
      "ram_capacity": "13.48 GB",
      "ram_unused": "15.39 KB"
    },
    "gpu": {
      "type": "AmdOpenCL",
      "vram_recommended_capacity": 0,
      "vram_unused": 0
    },
    "os": {
      "platform": "linux",
      "version": "6.5.0-28-generic",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.20",
      "downloadsDir": "/home/javila/.cache/lm-studio/models"
    },
    "model": {}
  },
  "title": "Error loading model."
}

**Comment by aijdsofttech** [comment]
I have a the same error in Ubuntu 20.04 LTS

**Comment by nitishpatel** [comment]
"memory": {
    "ram_capacity": "14.94 GB",
    "ram_unused": "24.25 KB"
  },
  "gpu": {
    "type": "AmdOpenCL",
    "vram_recommended_capacity": 0,
    "vram_unused": 0
  },
  "os": {
    "platform": "linux",
    "version": "6.5.0-27-generic",
    "supports_avx2": true
  },
  "app": {
    "version": "0.2.20",
    "downloadsDir": "/home/ntsh/.cache/lm-studio/models"
  },
  "model": {}
}

**Comment by sobvan** [comment]
I deleted LM Studio, downloaded it again from the site, and it worked.
I think the auto update could have messed something up.

**Comment by kriserickson** [comment]
Same error here, clean install, updated C++ redistributables.  Old CPU but lots of ram.  Happens with every model I have tried.

{
  "memory": {
    "ram_capacity": "31.94 GB",
    "ram_unused": "20.38 GB"
  },
  "gpu": {
    "type": "NvidiaCuda",
    "vram_recommended_capacity": 0,
    "vram_unused": 0
  },
  "os": {
    "platform": "win32",
    "version": "10.0.19045",
    "supports_avx2": true
  },
  "app": {
    "version": "0.2.20",
    "downloadsDir": "C:\\Users\\kris\\.cache\\lm-studio\\models"
  },
  "model": {}
}

**Comment by d-d** [comment]
> I deleted LM Studio, downloaded it again from the site, and it worked. I think the auto update could have messed something up.

Something is going with the installation process.

I had the same issue (error 42) on Mac. A fresh install from brew.
Seeing this comment, I just reinstalled

`brew reinstall --cask lm-studio`

and it worked!

**Comment by yagil** [comment]
Error 42 on **Mac** was caused by an issue in our build system, sorry about that.
If you redownload from the website it should work: https://lmstudio.ai

**Comment by peterxie1** [comment]
> Error 42 on **Mac** was caused by an issue in our build system, sorry about that. If you redownload from the website it should work: https://lmstudio.ai

Does this fix also help get it working on Ubuntu Linux? Thanks.

**Comment by manu-git-code** [comment]
Still getting this on Linux (PopOs) on app version 0.2.21. I've tried a couple of models. 

```json
{
  "cause": "(Exit code: 0). Please check settings and try loading the model again. ",
  "suggestion": "",
  "data": {
    "memory": {
      "ram_capacity": "30.50 GB",
      "ram_unused": "50.50 KB"
    },
    "gpu": {
      "type": "AmdOpenCL",
      "vram_recommended_capacity": 0,
      "vram_unused": 0
    },
    "os": {
      "platform": "linux",
      "version": "6.8.0-76060800daily20240311-generic",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.21",
      "downloadsDir": "/media/ai_models"
    },
    "model": {}
  },
  "title": "Error loading model."
}```

**Comment by roooychen** [comment]
I encountered (exit code: 139) when I set the wrong hardware setting.
If you don't have a GPU card, just uncheck "Hardware Settings > GPU Acceleration > GPU Offload".

**Comment by manu-git-code** [comment]
> I encountered (exit code: 139) when I set the wrong hardware setting. If you don't have a GPU card, just uncheck "Hardware Settings > GPU Acceleration > GPU Offload".

That worked! I've an AMD 7700XT, I guess it is not supported at the moment? 

Thanks :)

**Comment by emreds** [comment]
> I encountered (exit code: 139) when I set the wrong hardware setting. If you don't have a GPU card, just uncheck "Hardware Settings > GPU Acceleration > GPU Offload".

Also worked for me with an AMD GPU. Thanks a lot!

**Comment by haraldschilly** [comment]
Dumb question: where are these "Hardware Settings"? I'm on Linux, maybe they aren't shown?

**Comment by emreds** [comment]
> Dumb question: where are these "Hardware Settings"? I'm on Linux, maybe they aren't shown?

On the AI Chat section, there is a Settings Sidebar on the right. Click the Advanced Settings in Settings Sidebar and you will see. It took me a while to find it.

**Comment by haraldschilly** [comment]
> > Dumb question: where are these "Hardware Settings"? I'm on Linux, maybe they aren't shown?
> 
> On the AI Chat section, there is a Settings Sidebar on the right. Click the Advanced Settings in Settings Sidebar and you will see. It took me a while to find it.

Ahh, thank you! It's buried in "Advanced Configuration" :face_with_spiral_eyes:

**Comment by ajayfaul** [comment]
It would be better if this issue can be fixed for integrated AMD GPU and use the use the VRAM

**Comment by aijdsofttech** [comment]
Facing the Same Issue with 20.04 LTS Ubuntu LM_Studio-0.2.21.AppImage 
  "memory": {
    "ram_capacity": "125.57 GB",
    "ram_unused": "127.57 KB"
  },
  "gpu": {
    "type": "NvidiaCuda",
    "vram_recommended_capacity": "47.33 GB",
    "vram_unused": "46.97 GB"
  },
  "os": {
    "platform": "linux",
    "version": "5.15.0-105-generic",
    "supports_avx2": true
  },
  "app": {
    "version": "0.2.21",
    "downloadsDir": "/home/unlimitedwp/.cache/lm-studio/models"
  },
  "model": {}
```
{
  "memory": {
    "ram_capacity": "125.57 GB",
    "ram_unused": "127.57 KB"
  },
  "gpu": {
    "type": "NvidiaCuda",
    "vram_recommended_capacity": "47.33 GB",
    "vram_unused": "46.97 GB"
  },
  "os": {
    "platform": "linux",
    "version": "5.15.0-105-generic",
    "supports_avx2": true
  },
  "app": {
    "version": "0.2.21",
    "downloadsDir": "/home/unlimitedwp/.cache/lm-studio/models"
  },
  "model": {}
```

**Comment by ericlay** [comment]
> I encountered (exit code: 139) when I set the wrong hardware setting. If you don't have a GPU card, just uncheck "Hardware Settings > GPU Acceleration > GPU Offload".

Oh wow, embarrassed I posted this without attempting that. This indeed does work on both Arch and Debian installs for me. 

Closing now as this may just be pebcak.

**Comment by mateitudose** [comment]
This solution does not appear to be optimal, as the inference process on the CPU is significantly slow. I suggest reopening the issue

**Comment by peterxie1** [comment]
> I saw the same issue, cannot load any models with LM studio 0.2.18 on Ubuntu20.04. i saw error: "(exit code: 42)?. Please check settings and try loading the model again. " Anyone get it working on Linux?

on 0.2.18, errors when loading ANY model:
```json
{
  "cause": "(Exit code: 42)?. Please check settings and try loading the model again. ",
  "suggestion": "",
  "data": {
    "memory": {
      "ram_capacity": "251.39 GB",
      "ram_unused": "253.39 KB"
    },
    "gpu": {
      "type": "Unknown",
      "vram_recommended_capacity": 0,
      "vram_unused": 0
    },
    "os": {
      "platform": "linux",
      "version": "5.15.47+prerelease4757",
      "supports_avx2": true
    },
    "app": {
      "version": "0.2.18",
      "downloadsDir": "/home/gta/.cache/lm-studio/models"
    },
    "model": {}
  },
  "title": "Error loading model."
}```
========================================================
on 0.2.20 and 0.2.22 the LM Studio GUI does not even load, it crashed with the below:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_LM_Stu6pC27n/resources/app/.webpack/main/build/Release/NoGPU/liblmstudio_bindings.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1326:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at c (/tmp/.mount_LM_Stu6pC27n/resources/app/.webpack/main/index.js:2:2765)
    at 21587 (/tmp/.mount_LM_Stu6pC27n/resources/app/.webpack/main/index.js:8:650139)

**Comment by yagil** [comment]
Ubuntu 22.04 is the minimum required for the Linux version. We hope to support older Ubuntu as well, but that’s not in place right now.

**Comment by PixelOfDeath** [comment]
I hat the issue (0.2.22 on Xubuntu 23.10), that GPU mode is selected at first but causes the (Error code: 0) when trying to load a model.

I unselect "GPU Acceleration" and then it loads the models just fine.

But if I open a new chat and try to load (or reload) a model I get that error again. I have to then select AND unselect "GPU Acceleration" again to make it work in the context of that new chat.

**Comment by peterxie1** [comment]
> Ubuntu 22.04 is the minimum required for the Linux version. We hope to support older Ubuntu as well, but that’s not in place right now.

Thanks. I upgraded from Ubuntu 20.04 to Ubuntu 22.04 and LM Studio 0.2.22 appears to be working! it can load TheBloke's Mistral Instruct v0.2 7B Q4_K_S gguf model with no issue. Thanks again.

**Comment by javapapo** [comment]
I agree with the above. 

For example `ollam`- does manage to identify GPU capabilities on my thinkpad X13 (no matter if its not a very powerful GPU).


```
OS: Pop!_OS 22.04 LTS x86_64
GPU: AMD ATI 33:00.0 Rembrandt
```

this is the output from a fresh update of ollama locally on the same machine

```
>> Creating ollama systemd service...
>>> Enabling and starting ollama service...
>>> Downloading AMD GPU dependencies...
######################################################################## 100.0%##O#-#               ######################################################################## 100.0%
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
>>> AMD GPU dependencies installed.
```

It seems that LMStudio can not detect these capabilities on certain flavours of Ubuntu or Debian based machines - not sure.

**Comment by Archana-M-123** [comment]
> I hat the issue (0.2.22 on Xubuntu 23.10), that GPU mode is selected at first but causes the (Error code: 0) when trying to load a model.
> 
> I unselect "GPU Acceleration" and then it loads the models just fine.
> 
> But if I open a new chat and try to load (or reload) a model I get that error again. I have to then select AND unselect "GPU Acceleration" again to make it work in the context of that new chat.

Thank u its working fyn

**Comment by redet-G** [comment]
I bootstrapped `lms` and disabled gup by running  the following command. It is now working fine.
```
lms load --gpu=0
````
