### ISSUE TITLE
Failed to Start LM Studio Mac M1 (Error EACCES permission denied)

### ISSUE THREAD

**Issue by peter-id-labs** [lmstudio-ai/.github#47]
Cant start LM Studio, Error: EACCES: permission denied, open '/Users/peter.id/.cache/lm-studio/config-presets/default_lm_studio_macos.preset.json'

<img width="258" alt="Screenshot 2024-05-02 at 10 55 51" src="https://github.com/lmstudio-ai/.github/assets/85329103/4e62e3e7-da93-4f10-9486-aecefcd187ae">

**Comment by yagil** [comment]
@peter-id-labs did you first drag the app into your Applications folder, or did you run it directly from the initial window it showed?

<img width="772" alt="image" src="https://github.com/lmstudio-ai/.github/assets/3611042/0b16d535-c747-4dbc-b1ac-60ca37a6dde3">

**Comment by yagil** [comment]
Could also be the same as this:
- https://github.com/lmstudio-ai/.github/issues/25#issuecomment-1962985576

**Comment by peter-id-labs** [comment]
@yagil I dragged LM Studio on Application folder

**Comment by peter-id-labs** [comment]
> Could also be the same as this:
> 
> * [Error on Startup (first install) [Workaround included] #25 (comment)](https://github.com/lmstudio-ai/.github/issues/25#issuecomment-1962985576)

Thank You this is work
