### ISSUE TITLE
[Windows 8] Getting "This app can't run on your PC" when I run setup.exe 

### ISSUE THREAD

**Issue by 3dfoster** [lmstudio-ai/.github#64]
I am trying to install LM-Studio-0.3.2-Setup on my Windows 11 laptop, however when I try to run I get the error message "This app can't run on your PC."

I used compatibility mode to run the exe as Windows 8 but that did not do anything.

<img width="511" alt="image" src="https://github.com/user-attachments/assets/0ee1d2cc-e68e-4b9f-b773-a2bf5f6e569a">

**Comment by yagil** [comment]
Hi @3dfoster thanks for the bug report. We only have testing coverage for Windows 10 and 11, so it's very likely the app will not work on older versions of Windows.
